#!/bin/bash
##################################################################################
# Description
##################################################################################
# This configuration file is for the verification land mask used throughout the
# workflow.  This defines the locations of landmask lat-lon text files and
# outputs as generated by vxmask in MET.
#
##################################################################################
# Mask Parameters
##################################################################################
# Source HPC parameters
source ../config_MET-tools.sh

# Verification region group name
export VRF_RGN=CA_All

# Path to lat-lon text files for mask generation
export MSK_LTLN=${MSK_ROOT}/lat-lon

# Path to file with list of landmasks for verification regions
export MSK_LST=${MSK_ROOT}/mask-lists/${VRF_RGN}_MaskList.txt

# Root directory of regridded .nc landmasks on StageIV domain for verification
export MSK_GRDS=${MSK_ROOT}/${VRF_RGN}_Masks

# Generic StageIV data product for reference verfication grid in ${MSK_ROOT}
export OBS_F_IN=StageIV_QPE_2019021500.nc
